"use client";

import React from "react";
import {
  LayoutDashboard,
  Bot,
  ShoppingCart,
  Calendar,
  User,
  CheckSquare,
  FileText,
  Table,
  Layers,
  MessageSquare,
  Headphones,
  Mail,
  PieChart,
  MapPin,
  Component,
  Lock,
  ChevronDown,
  ChevronRight,
  Search,
  Bell,
  Sun,
  Moon,
  Menu,
  X,
  Plus,
  ArrowUpRight,
  ArrowDownRight,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Users,
  Eye,
  ShoppingBag,
  Clock,
  Sparkles,
  Zap,
  Check,
  Filter,
  Download,
  Share2,
  MoreVertical,
  Trash2,
  Edit,
  Sliders,
  Play,
  Pause,
  Copy,
  ExternalLink,
  Code,
  Image as ImageIcon,
  Video,
  FileCode,
  Key,
  Shield,
  HelpCircle,
  AlertCircle,
  Inbox,
  Send,
  Paperclip,
  Activity,
  Globe,
  Settings,
  Grid,
  List as ListIcon,
  BarChart2,
  CreditCard,
  Package,
  Truck,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  ChevronLeft,
} from "lucide-react";

interface IconProps {
  name: string;
  className?: string;
  size?: number;
}

export function DynamicIcon({ name, className = "w-5 h-5", size = 20 }: IconProps) {
  const iconMap: Record<string, React.ReactNode> = {
    LayoutDashboard: <LayoutDashboard size={size} className={className} />,
    Bot: <Bot size={size} className={className} />,
    ShoppingCart: <ShoppingCart size={size} className={className} />,
    Calendar: <Calendar size={size} className={className} />,
    User: <User size={size} className={className} />,
    CheckSquare: <CheckSquare size={size} className={className} />,
    FileText: <FileText size={size} className={className} />,
    Table: <Table size={size} className={className} />,
    Layers: <Layers size={size} className={className} />,
    MessageSquare: <MessageSquare size={size} className={className} />,
    Headphones: <Headphones size={size} className={className} />,
    Mail: <Mail size={size} className={className} />,
    PieChart: <PieChart size={size} className={className} />,
    MapPin: <MapPin size={size} className={className} />,
    Component: <Component size={size} className={className} />,
    Lock: <Lock size={size} className={className} />,
    ChevronDown: <ChevronDown size={size} className={className} />,
    ChevronRight: <ChevronRight size={size} className={className} />,
    Search: <Search size={size} className={className} />,
    Bell: <Bell size={size} className={className} />,
    Sun: <Sun size={size} className={className} />,
    Moon: <Moon size={size} className={className} />,
    Menu: <Menu size={size} className={className} />,
    X: <X size={size} className={className} />,
    Plus: <Plus size={size} className={className} />,
    ArrowUpRight: <ArrowUpRight size={size} className={className} />,
    ArrowDownRight: <ArrowDownRight size={size} className={className} />,
    TrendingUp: <TrendingUp size={size} className={className} />,
    TrendingDown: <TrendingDown size={size} className={className} />,
    DollarSign: <DollarSign size={size} className={className} />,
    Users: <Users size={size} className={className} />,
    Eye: <Eye size={size} className={className} />,
    ShoppingBag: <ShoppingBag size={size} className={className} />,
    Clock: <Clock size={size} className={className} />,
    Sparkles: <Sparkles size={size} className={className} />,
    Zap: <Zap size={size} className={className} />,
    Check: <Check size={size} className={className} />,
    Filter: <Filter size={size} className={className} />,
    Download: <Download size={size} className={className} />,
    Share2: <Share2 size={size} className={className} />,
    MoreVertical: <MoreVertical size={size} className={className} />,
    Trash2: <Trash2 size={size} className={className} />,
    Edit: <Edit size={size} className={className} />,
    Sliders: <Sliders size={size} className={className} />,
    Play: <Play size={size} className={className} />,
    Pause: <Pause size={size} className={className} />,
    Copy: <Copy size={size} className={className} />,
    ExternalLink: <ExternalLink size={size} className={className} />,
    Code: <Code size={size} className={className} />,
    ImageIcon: <ImageIcon size={size} className={className} />,
    Video: <Video size={size} className={className} />,
    FileCode: <FileCode size={size} className={className} />,
    Key: <Key size={size} className={className} />,
    Shield: <Shield size={size} className={className} />,
    HelpCircle: <HelpCircle size={size} className={className} />,
    AlertCircle: <AlertCircle size={size} className={className} />,
    Inbox: <Inbox size={size} className={className} />,
    Send: <Send size={size} className={className} />,
    Paperclip: <Paperclip size={size} className={className} />,
    Activity: <Activity size={size} className={className} />,
    Globe: <Globe size={size} className={className} />,
    Settings: <Settings size={size} className={className} />,
    Grid: <Grid size={size} className={className} />,
    ListIcon: <ListIcon size={size} className={className} />,
    BarChart2: <BarChart2 size={size} className={className} />,
    CreditCard: <CreditCard size={size} className={className} />,
    Package: <Package size={size} className={className} />,
    Truck: <Truck size={size} className={className} />,
    CheckCircle2: <CheckCircle2 size={size} className={className} />,
    XCircle: <XCircle size={size} className={className} />,
    AlertTriangle: <AlertTriangle size={size} className={className} />,
    Info: <Info size={size} className={className} />,
    ChevronLeft: <ChevronLeft size={size} className={className} />,
  };

  return iconMap[name] || <Component size={size} className={className} />;
}
