"use client";

import React, { useState } from "react";
import Link from "next/link";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Breadcrumb } from "@/components/layout/Breadcrumb";
import { ArrowLeft, Star, Reply, Forward, Trash2, Archive, Send, Paperclip } from "lucide-react";

export default function InboxDetailsPage() {
  const [replyOpen, setReplyOpen] = useState(false);
  const [replyText, setReplyText] = useState("");

  return (
    <DashboardLayout>
      <Breadcrumb pageTitle="Email Details" category="Email" categoryHref="/inbox" />

      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center justify-between">
          <Link
            href="/inbox"
            className="flex items-center gap-1.5 text-xs text-zinc-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Inbox</span>
          </Link>

          <div className="flex items-center gap-2 text-zinc-400">
            <button className="p-2 hover:text-white rounded hover:bg-zinc-900 transition-colors">
              <Archive className="w-4 h-4" />
            </button>
            <button className="p-2 hover:text-white rounded hover:bg-zinc-900 transition-colors">
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="mono-card p-6 sm:p-8 space-y-6">
          {/* Subject & Meta */}
          <div className="pb-6 border-b border-zinc-800">
            <h2 className="text-lg font-bold text-white mb-3">
              [Security Alert] Dependency vulnerability detected in package.json
            </h2>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-zinc-800 border border-zinc-700 font-bold text-xs text-white flex items-center justify-center">
                  GH
                </div>
                <div>
                  <span className="text-xs font-bold text-white block">
                    GitHub Security Advisories
                  </span>
                  <span className="text-[11px] text-zinc-400">notifications@github.com</span>
                </div>
              </div>

              <div className="text-right">
                <span className="text-[11px] text-zinc-500 font-mono">
                  24 Oct 2026, 10:45 AM (2 hours ago)
                </span>
              </div>
            </div>
          </div>

          {/* Email Body */}
          <div className="prose prose-invert max-w-none text-xs text-zinc-300 leading-relaxed space-y-4">
            <p>Hello @musharof,</p>

            <p>
              Dependabot has evaluated your active dependency graph and identified 1 potential
              advisory impacting your production bundle.
            </p>

            <div className="p-4 rounded-xl bg-zinc-950 border border-zinc-800 font-mono text-xs text-zinc-300 space-y-1">
              <div>
                <strong>Package:</strong> cross-spawn (npm)
              </div>
              <div>
                <strong>Advisory ID:</strong> GHSA-3xgq-45jj-v275
              </div>
              <div>
                <strong>Severity:</strong> Moderate (CVSS 6.8)
              </div>
              <div>
                <strong>Recommended Version:</strong> &gt;= 7.0.6
              </div>
            </div>

            <p>
              We recommend reviewing the automated pull request generated by Dependabot or running{" "}
              <code className="px-1.5 py-0.5 rounded bg-zinc-900 text-white font-mono">
                npm audit fix
              </code>{" "}
              to remediate this issue.
            </p>

            <p className="pt-4 text-zinc-500">
              Best regards,
              <br />
              The GitHub Security Team
            </p>
          </div>

          {/* Reply Section */}
          <div className="pt-6 border-t border-zinc-800">
            {!replyOpen ? (
              <div className="flex gap-3">
                <button
                  onClick={() => setReplyOpen(true)}
                  className="px-4 py-2 bg-white text-black font-bold text-xs rounded-lg hover:bg-zinc-200 transition-colors flex items-center gap-1.5"
                >
                  <Reply className="w-3.5 h-3.5" />
                  <span>Reply</span>
                </button>
                <button
                  onClick={() => setReplyOpen(true)}
                  className="px-4 py-2 bg-zinc-900 border border-zinc-700 text-white text-xs font-semibold rounded-lg hover:bg-zinc-800 transition-colors flex items-center gap-1.5"
                >
                  <Forward className="w-3.5 h-3.5" />
                  <span>Forward</span>
                </button>
              </div>
            ) : (
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  setReplyOpen(false);
                }}
                className="space-y-3"
              >
                <textarea
                  rows={4}
                  placeholder="Write your email reply..."
                  value={replyText}
                  onChange={(e) => setReplyText(e.target.value)}
                  className="w-full bg-zinc-900 border border-zinc-700 text-white rounded-lg p-3 text-xs focus:outline-none focus:border-white placeholder-zinc-500"
                />
                <div className="flex items-center justify-between">
                  <button
                    type="button"
                    onClick={() => setReplyOpen(false)}
                    className="text-xs text-zinc-400 hover:text-white"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 bg-white text-black font-bold text-xs rounded-lg hover:bg-zinc-200 transition-colors flex items-center gap-1.5"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Send</span>
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
