"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ShieldCheck, ArrowRight, ArrowLeft } from "lucide-react";

export default function TwoStepVerificationPage() {
  const router = useRouter();
  const [digits, setDigits] = useState(["", "", "", "", "", ""]);

  const handleChange = (index: number, val: string) => {
    if (val.length > 1) val = val.slice(-1);
    const newDigits = [...digits];
    newDigits[index] = val;
    setDigits(newDigits);

    if (val && index < 5) {
      const nextInput = document.getElementById(`digit-${index + 1}`);
      nextInput?.focus();
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    router.push("/");
  };

  return (
    <div className="min-h-screen bg-[#050507] flex flex-col items-center justify-center p-6 bg-mono-dots relative">
      <div className="w-full max-w-md space-y-6 mono-card p-8 sm:p-10 border-zinc-700 bg-zinc-950/80 shadow-2xl">
        <div className="text-center space-y-2">
          <div className="w-12 h-12 rounded-2xl bg-white text-black font-extrabold text-xl flex items-center justify-center mx-auto mb-3 shadow-xl">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <h1 className="text-2xl font-extrabold text-white">Two-Factor Authentication</h1>
          <p className="text-xs text-zinc-400">
            Enter the 6-digit authentication code generated by your Authenticator app
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6 pt-2">
          <div className="flex justify-between gap-2">
            {digits.map((digit, idx) => (
              <input
                key={idx}
                id={`digit-${idx}`}
                type="text"
                maxLength={1}
                value={digit}
                onChange={(e) => handleChange(idx, e.target.value)}
                className="w-12 h-12 text-center text-lg font-mono font-bold bg-zinc-900 border border-zinc-700 text-white rounded-xl focus:outline-none focus:border-white focus:ring-1 focus:ring-white transition-all"
              />
            ))}
          </div>

          <button
            type="submit"
            className="w-full py-2.5 bg-white text-black font-bold text-xs rounded-lg hover:bg-zinc-200 transition-colors shadow-sm flex items-center justify-center gap-2"
          >
            <span>Verify & Authenticate</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </form>

        <div className="pt-4 border-t border-zinc-800 text-center text-xs text-zinc-400">
          Haven't received code?{" "}
          <button className="text-white font-semibold hover:underline">Resend SMS / Push</button>
        </div>
      </div>
    </div>
  );
}
